-keepnames class com.odnovolov.forgetmenot.presentation.screen.home.adddeck.AddDeckFragment
-keepnames class com.odnovolov.forgetmenot.presentation.screen.exampleexercise.ExampleExerciseFragment
-keepnames class com.odnovolov.forgetmenot.presentation.screen.exampleplayer.ExamplePlayerFragment