-keep class com.odnovolov.forgetmenot.presentation.screen.home.addcards.AddCardsFragment
-keepnames class com.odnovolov.forgetmenot.presentation.screen.exampleexercise.ExampleExerciseFragment
-keepnames class com.odnovolov.forgetmenot.presentation.screen.exampleplayer.ExamplePlayerFragment
-keep class com.odnovolov.forgetmenot.presentation.screen.fileimport.cardsfile.sourcetext.fileformat.FileFormatFragment